# Generated by Django 5.1.1 on 2024-09-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecategory',
            old_name='sale_id',
            new_name='sale',
        ),
    ]
