# Generated by Django 5.1.1 on 2024-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_district_region_user_district_district_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='users'),
            preserve_default=False,
        ),
    ]
