# Generated by Django 5.1.1 on 2024-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
